//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPT> DEPTs { get; set; }
        public DbSet<EMP> EMPs { get; set; }
        public DbSet<EMP00> EMP00 { get; set; }
        public DbSet<FruitProduct> FruitProducts { get; set; }
        public DbSet<FruitProducts1> FruitProducts1 { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<Movy> Movies1 { get; set; }
        public DbSet<MSreplication_options> MSreplication_options { get; set; }
        public DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public DbSet<spt_monitor> spt_monitor { get; set; }
        public DbSet<spt_values> spt_values { get; set; }
    
        public virtual int DELETEEMP(Nullable<decimal> eMPNO)
        {
            var eMPNOParameter = eMPNO.HasValue ?
                new ObjectParameter("EMPNO", eMPNO) :
                new ObjectParameter("EMPNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEEMP", eMPNOParameter);
        }
    
        public virtual ObjectResult<EMP0_Result> EMP0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EMP0_Result>("EMP0");
        }
    
        public virtual ObjectResult<GetFruitProduct_Result> GetFruitProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFruitProduct_Result>("GetFruitProduct");
        }
    
        public virtual ObjectResult<GetFruitProducts_Result> GetFruitProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFruitProducts_Result>("GetFruitProducts");
        }
    
        public virtual ObjectResult<GetFruitProducts1_Result> GetFruitProducts1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFruitProducts1_Result>("GetFruitProducts1");
        }
    
        public virtual int InsertEmp(Nullable<decimal> eMPNO, string eNAME, string jOB, Nullable<decimal> mGR, Nullable<decimal> sAL, Nullable<decimal> cOMM, Nullable<decimal> dEPTNO)
        {
            var eMPNOParameter = eMPNO.HasValue ?
                new ObjectParameter("EMPNO", eMPNO) :
                new ObjectParameter("EMPNO", typeof(decimal));
    
            var eNAMEParameter = eNAME != null ?
                new ObjectParameter("ENAME", eNAME) :
                new ObjectParameter("ENAME", typeof(string));
    
            var jOBParameter = jOB != null ?
                new ObjectParameter("JOB", jOB) :
                new ObjectParameter("JOB", typeof(string));
    
            var mGRParameter = mGR.HasValue ?
                new ObjectParameter("MGR", mGR) :
                new ObjectParameter("MGR", typeof(decimal));
    
            var sALParameter = sAL.HasValue ?
                new ObjectParameter("SAL", sAL) :
                new ObjectParameter("SAL", typeof(decimal));
    
            var cOMMParameter = cOMM.HasValue ?
                new ObjectParameter("COMM", cOMM) :
                new ObjectParameter("COMM", typeof(decimal));
    
            var dEPTNOParameter = dEPTNO.HasValue ?
                new ObjectParameter("DEPTNO", dEPTNO) :
                new ObjectParameter("DEPTNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEmp", eMPNOParameter, eNAMEParameter, jOBParameter, mGRParameter, sALParameter, cOMMParameter, dEPTNOParameter);
        }
    
        public virtual int InsertEmployee(Nullable<decimal> eMPNO, string eNAME, string jOB, Nullable<decimal> mGR, Nullable<decimal> sAL, Nullable<decimal> cOMM, Nullable<decimal> dEPTNO)
        {
            var eMPNOParameter = eMPNO.HasValue ?
                new ObjectParameter("EMPNO", eMPNO) :
                new ObjectParameter("EMPNO", typeof(decimal));
    
            var eNAMEParameter = eNAME != null ?
                new ObjectParameter("ENAME", eNAME) :
                new ObjectParameter("ENAME", typeof(string));
    
            var jOBParameter = jOB != null ?
                new ObjectParameter("JOB", jOB) :
                new ObjectParameter("JOB", typeof(string));
    
            var mGRParameter = mGR.HasValue ?
                new ObjectParameter("MGR", mGR) :
                new ObjectParameter("MGR", typeof(decimal));
    
            var sALParameter = sAL.HasValue ?
                new ObjectParameter("SAL", sAL) :
                new ObjectParameter("SAL", typeof(decimal));
    
            var cOMMParameter = cOMM.HasValue ?
                new ObjectParameter("COMM", cOMM) :
                new ObjectParameter("COMM", typeof(decimal));
    
            var dEPTNOParameter = dEPTNO.HasValue ?
                new ObjectParameter("DEPTNO", dEPTNO) :
                new ObjectParameter("DEPTNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertEmployee", eMPNOParameter, eNAMEParameter, jOBParameter, mGRParameter, sALParameter, cOMMParameter, dEPTNOParameter);
        }
    
        public virtual ObjectResult<SelectEmp_Result> SelectEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectEmp_Result>("SelectEmp");
        }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    
        public virtual int UpdateEmp(Nullable<decimal> eMPNO, string eNAME, Nullable<decimal> sAL)
        {
            var eMPNOParameter = eMPNO.HasValue ?
                new ObjectParameter("EMPNO", eMPNO) :
                new ObjectParameter("EMPNO", typeof(decimal));
    
            var eNAMEParameter = eNAME != null ?
                new ObjectParameter("ENAME", eNAME) :
                new ObjectParameter("ENAME", typeof(string));
    
            var sALParameter = sAL.HasValue ?
                new ObjectParameter("SAL", sAL) :
                new ObjectParameter("SAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEmp", eMPNOParameter, eNAMEParameter, sALParameter);
        }
    }
}
